### ISSUE TITLE
extrideur, termistore and fan

### ISSUE THREAD

**Issue by mohamedamineamdouni** [Wallacoloo/printipi#93]
i can't make a connection between the extrideur the fan th termistor with the RPI 
can you help me with circuit schema please !

**Comment by Wallacoloo** [comment]
The Raspberry Pi has no analog inputs, so you have to use something like a RC circuit and measure its time constant to determine the temperature at the thermistor.

The schematic for my approach is documented in the code [here](https://github.com/Wallacoloo/printipi/blob/master/src/iodrivers/rcthermistor2pin.h#L41), and then I instantiate it [here](https://github.com/Wallacoloo/printipi/blob/master/src/machines/rpi/kosselrampsfd.h#L525).

The hotend and fan are straightforward. Just connect a gpio on the Pi to the base of a mosfet, and have the mosfet drive the fan/hotend. A circuit like [this](http://i.stack.imgur.com/6UWgb.png) would work, for example. For the fan, just replace the resistor in that schematic with your fan. 

For most 3d printers, the extruder is just like any other stepper motor. In [my configuration](https://github.com/Wallacoloo/printipi/blob/master/src/machines/rpi/kosselrampsfd.h#L560), I'm using a delta bot, and the extruder is just the fourth axis.
